
const LOGIN = 'LOGIN';
const GETSESSIONDATA = 'GETSESSIONDATA';
const LOGOUT = 'LOGOUT';
const ADDCARTITEM = 'ADDCARTITEM';
const REMOVECARTITEM = 'REMOVECARTITEM';
const CLEARCART = 'CLEARCART';

const SETACTIVEPRODUCT = 'SETACTIVEPRODUCT';
const REMOVEACTIVEPRODUCT = 'REMOVEACTIVEPRODUCT';

export {
    LOGIN,
    GETSESSIONDATA,
    LOGOUT,
    ADDCARTITEM,
    REMOVECARTITEM,
    CLEARCART,
    SETACTIVEPRODUCT,
    REMOVEACTIVEPRODUCT,
}